version: '3'
services:
  # Piwigo Service
  piwigo:
    image: linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - DB_HOST=database
      - DB_USER=piwigo
      - DB_PASS=piwigo_password
      - DB_NAME=piwigo_db
    ports:
      - "8080:80"
    volumes:
      - /home/student/project2/piwigo:/config
    depends_on:
      - database
    restart: always

  # Database Service (MySQL)
  database:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MyR00tP@ssword
      - MYSQL_USER=piwigo
      - MYSQL_PASSWORD=piwigo_password
      - MYSQL_DATABASE=piwigo_db
    volumes:
      - /home/student/project2/mysql:/var/lib/mysql
    restart: always
